---
title: "Assignment-5\n \\vspace{1in}"
output: pdf_document
date: "2023-03-31\n \\vspace{1in}"
author: "Imanbayeva Sofya, Mazzi Lapo, Piras Mattia, Srivastava Dev\n \\vspace{1in}"
subtitle: "Group 22\n \\vspace{1in}"
---

```{r setup, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = FALSE, out.height = "75%", out.width = "75%")
list.of.packages <- c("dlm", "fpp2", "forecast","ggplot2","depmixS4","tidyverse","dplyr","rlang","tseries","zoo")
if(!require(dlm)){
    install.packages("dlm")
    library(dlm)
}
if(!require(fpp2)){
    install.packages("fpp2")
    library(fpp2)
}
if(!require(forecast)){
    install.packages("forecast")
    library(forecast)
}
if(!require(ggplot2)){
    install.packages("ggplot2")
    library(ggplot2)
}
if(!require(depmixS4)){
    install.packages("depmixS4")
    library(depmixS4)
}
if(!require(markovchain)){
    install.packages("markovchain")
    library(markovchain)
}
if(!require(tidyverse)){
    install.packages("tidyverse")
    library(tidyverse)
}
if(!require(dplyr)){
    install.packages("dplyr")
    library(dplyr)
}
if(!require(rlang)){
    install.packages("rlang")
    library(rlang)
}
  if(!require(tseries)){
    install.packages("tseries")
    library(tseries)
  }
  if(!require(zoo)){
    install.packages("zoo")
    library(zoo)
}
```

```{r Nile graph}

plot(Nile, main = "Graph 1: River Nile annual flow in 10^8 cubic meters (1871-1970)", xlab = "Time", ylab= "Water flow in 10^8 cubic meters")
```
Let us consider the following random walk plus noise model to be applied to the Nile data:
\begin{eqnarray*} 
Y_t &= \theta_t + v_t \quad    & v_t \overset{i.i.d.}\sim N(0, V)\\
\theta_t &= \theta_{t-1} + w_t \quad   & v_t \overset{i.i.d.}\sim N(0, W)
\end{eqnarray*}

We will set V = 15100 and W = 1470 and the initial distribution $\theta_0 \sim N(1000,1000)$ for our model

```{r model}
mod <- dlm(m0=1000, C0=1000, FF=1, V=15100, GG=1, W=1470)
```
